# Generated by Django 2.0 on 2018-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thump',
            field=models.ImageField(blank=True, default='defaul.png', upload_to=''),
        ),
    ]
