# Generated by Django 2.0 on 2018-02-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thump'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thump',
            new_name='thumb',
        ),
    ]
